#!/usr/bin/env bash
# First-time deploy: rsync project + dump+restore DB + generate prod .env +
# write robots.txt + create top-level shim/.htaccess so Hostinger serves
# Ellev correctly without needing a custom DocumentRoot.
#
# Hard guarantee: refuses if Ellev already exists at target. There is no --force.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "${SCRIPT_DIR}/_lib.sh"

parse_args "$@"

build_ssh_args
remote_path=$(remote_base_path)

step "init deploy → ${ssh_target}:${remote_path}"

# --- 1) Refuse if Ellev already exists ---
state=$("${ssh_args[@]}" "test -f '${remote_path}/core/Bootstrap.php' && echo EXISTS || echo EMPTY" 2>&1)
if [[ "$state" == "EXISTS" ]]; then
    err "Ellev já está instalado em ${remote_path}."
    err "init sobrescreveria o site em produção (DB + arquivos) — bloqueado."
    err "Para alterações, use update-cms.sh ou update-theme.sh."
    err "Se você realmente quer recomeçar do zero, apague o conteúdo de ${remote_path} manualmente primeiro."
    exit 1
fi
ok "Target empty — proceeding"

# --- 2) Resolve config values needed for the deploy ---
domain=$(cfg_get '.site.domain')
app_url=$(cfg_get '.site.url')
subpath=$(cfg_get '.site.subpath' '')
db_name=$(cfg_get '.db.name')
db_user=$(cfg_get '.db.user')
db_pass=$(cfg_get '.db.password')
db_host=$(cfg_get '.db.host' 'localhost')
local_db_name=$(cfg_get '.local.db_name')

[[ -z "$app_url" || -z "$db_name" ]] && die "Config missing required fields (site.url, db.name)"

# Strip trailing slash from app_url
app_url="${app_url%/}"

# --- 3) Dump local DB ---
step "Dumping local DB '${local_db_name}'"
dump_file="/tmp/nano-init-$(date +%Y%m%d-%H%M%S).sql"
dump_cmd=$(local_db_dump_cmd)
if ! eval "$dump_cmd" > "$dump_file"; then
    err "mysqldump failed. Check local.* config."
    rm -f "$dump_file"
    exit 1
fi
dump_size=$(wc -c < "$dump_file")
ok "Dump: ${dump_file} (${dump_size} bytes)"

# --- 4) Rsync project files ---
step "Rsync project files"
rsh=$(rsync_remote_shell)
rsync_dest=$(rsync_target_for "$remote_path")

# Build exclude list. Defaults + user-supplied extras.
excludes=(
    --exclude=.env
    --exclude=.env.*
    --exclude=.git/
    --exclude=.github/
    --exclude=.deploy/
    --exclude=.claude/
    --exclude=.DS_Store
    --exclude=Thumbs.db
    --exclude=node_modules/
    --exclude=storage/cache/*
    --exclude=storage/logs/*
    --exclude=*.bak
    --exclude=*.swp
    # legacy ellev:theme-convert leftovers (top-level theme PHPs)
    --exclude=theme/*.php
    --exclude=theme/includes/
)

# Append user-provided extra excludes
while IFS= read -r ex; do
    [[ -n "$ex" ]] && excludes+=("--exclude=$ex")
done < <(jq -r '.rsync.extra_excludes[]? // empty' "$CONFIG_PATH")

# Ensure remote dir exists
"${ssh_args[@]}" "mkdir -p '${remote_path}'"

# Rsync project root → remote
if ! rsync -avz --delete-after \
    "${excludes[@]}" \
    -e "$rsh" \
    "./" "${rsync_dest}/" >&2; then
    err "rsync failed"
    rm -f "$dump_file"
    exit 1
fi
ok "Files synced"

# --- 5) Generate and upload .env (prod) ---
step "Writing remote .env"
env_tmp=$(mktemp)
cat > "$env_tmp" <<EOF
# Generated by nano-deploy-hostinger init on $(date -u +%Y-%m-%dT%H:%M:%SZ)
APP_NAME="${domain}"
APP_URL="${app_url}"
APP_DEBUG=false
APP_TIMEZONE=America/Sao_Paulo
APP_LOCALE=pt_BR
EOF
if [[ -n "$subpath" && "$subpath" != "/" ]]; then
    echo "APP_BASE_PATH=\"${subpath}\"" >> "$env_tmp"
fi
cat >> "$env_tmp" <<EOF

DB_DRIVER=mysql
DB_HOST=${db_host}
DB_PORT=3306
DB_DATABASE=${db_name}
DB_USERNAME=${db_user}
DB_PASSWORD="${db_pass}"

SESSION_NAME=nano_session
SESSION_LIFETIME=604800

SMTP_HOST=""
SMTP_PORT=587
SMTP_USER=""
SMTP_PASS=""
SMTP_FROM="${domain} <noreply@${domain}>"
EOF

# Use scp via the same alias/direct args
if [[ -n "$(cfg_get '.ssh.alias')" ]]; then
    scp -q "$env_tmp" "$(cfg_get '.ssh.alias'):${remote_path}/.env"
else
    port=$(cfg_get '.ssh.port' '22')
    key=$(cfg_get '.ssh.key_path' "$HOME/.ssh/id_ed25519")
    key="${key/#\~/$HOME}"
    user=$(cfg_get '.ssh.user')
    host=$(cfg_get '.ssh.host')
    scp -q -P "$port" -i "$key" "$env_tmp" "${user}@${host}:${remote_path}/.env"
fi
rm -f "$env_tmp"
"${ssh_args[@]}" "chmod 0640 '${remote_path}/.env'"
ok ".env written and chmod 0640"

# --- 6) Upload SQL dump and import ---
step "Uploading dump and importing into '${db_name}'"
remote_dump_path="/tmp/nano-init-import-$$.sql"
if [[ -n "$(cfg_get '.ssh.alias')" ]]; then
    scp -q "$dump_file" "$(cfg_get '.ssh.alias'):${remote_dump_path}"
else
    port=$(cfg_get '.ssh.port' '22')
    key=$(cfg_get '.ssh.key_path' "$HOME/.ssh/id_ed25519")
    key="${key/#\~/$HOME}"
    user=$(cfg_get '.ssh.user')
    host=$(cfg_get '.ssh.host')
    scp -q -P "$port" -i "$key" "$dump_file" "${user}@${host}:${remote_dump_path}"
fi

import_out=$("${ssh_args[@]}" "mysql -h${db_host} -u${db_user} -p'${db_pass}' ${db_name} < ${remote_dump_path} 2>&1 && rm -f ${remote_dump_path}" || true)
if [[ -n "$import_out" ]] && echo "$import_out" | grep -qi "error"; then
    err "MySQL import failed: $import_out"
    rm -f "$dump_file"
    exit 1
fi
ok "DB imported"
rm -f "$dump_file"

# --- 7) Run migrate (idempotent — catches any schema gap between dump and current code) ---
step "Running php bin/nano migrate"
mig_out=$("${ssh_args[@]}" "cd '${remote_path}' && php bin/nano migrate 2>&1" || true)
echo "$mig_out" | sed 's/^/  /' >&2
ok "Migrations OK"

# --- 8) Overwrite robots.txt with prod sitemap URL ---
# Ellev's flat layout puts robots.txt at the project root. The rsync above
# already shipped a robots.txt (copied by Installer from robots.txt.example)
# but it points at example.com — overwrite with the real APP_URL.
step "Writing robots.txt with production sitemap URL"
robots_tmp=$(mktemp)
cat > "$robots_tmp" <<EOF
User-agent: *
Allow: /
Disallow: /admin
Disallow: /admin/

Sitemap: ${app_url}/sitemap.xml
EOF
if [[ -n "$(cfg_get '.ssh.alias')" ]]; then
    scp -q "$robots_tmp" "$(cfg_get '.ssh.alias'):${remote_path}/robots.txt"
else
    port=$(cfg_get '.ssh.port' '22')
    key=$(cfg_get '.ssh.key_path' "$HOME/.ssh/id_ed25519")
    key="${key/#\~/$HOME}"
    user=$(cfg_get '.ssh.user')
    host=$(cfg_get '.ssh.host')
    scp -q -P "$port" -i "$key" "$robots_tmp" "${user}@${host}:${remote_path}/robots.txt"
fi
rm -f "$robots_tmp"
ok "robots.txt written with Sitemap: ${app_url}/sitemap.xml"

# Note: no top-level shim needed. Ellev's flat layout puts index.php and
# .htaccess at the project root already (rsynced from local), so Apache
# serves them directly. The .htaccess shipped with Ellev blocks core/, bin/,
# migrations/, theme/*.php, .env, etc.

# --- 9) Verify with curl ---
step "Verifying ${app_url}"
http_code=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 15 -L "${app_url}/" || echo 000)
if [[ "$http_code" == "200" ]]; then
    ok "HTTP 200 OK"
else
    warn "HTTP ${http_code} — site may need a moment to warm up. Check manually: ${app_url}"
fi

echo
ok "Init deploy complete."
echo
echo "  Site:   ${app_url}"
echo "  Admin:  ${app_url}/admin/login"
echo "  Path:   ${remote_path}"
echo
echo "Próximos passos:"
echo "  - Acessa o admin e confirma que o conteúdo migrou"
echo "  - Configurar SMTP em .env se forms forem enviar e-mail"
echo "  - Para mudanças de tema:  scripts/update-theme.sh --config ${CONFIG_PATH}"
echo "  - Para mudanças de core:  scripts/update-cms.sh   --config ${CONFIG_PATH}"
